---
title: "README"
author: "Isaac Rosenthal"
date: "September 11, 2015"
output: html_document
---
This is my README.

####Markdown Formats
To make that heading, I put #### in front of my text. The text size can be changed by increasing or decreasing the number of #s.

The text can be made *italic* or **bold** by placing surrounding text with single or double *, respectively. Additonally, _ may be used instead of *, allowing more elaborate formatting.

In order to save this README, I saved it into a directory on my computer located at C:\Users\Rosen_000\Documents\R projects\Practical computing\homework

We will be using GIT to track our changes. Initially, I tracked them on my local computer by using the following commands:

1. cd documents/'R projects'/'practical computing/homework
  *this gets me into the correct working directory
2. git status
  * this shows what branch I'm on and what files are there.
3. git add README.Rmd
  * This adds the file to the staging area
4. git commit -m 'preliminary README'
  * THis commits the file with a message to future me

I then made a repository on the github website used the following command to initiate it
>git remote add origin https://github.com/Isaac-Rosenthal/Intro-to-practical-computing.git

I checked that it worked by doing
>git remote -v

Finally, I pushed my local file to the remote repository by doing:
>git push origin master

I entered my login info when prompted, and as you are reading this online it has clearly worked.


